datas: "/home/azadeh/Documents/Data_test_europ_2023/FASTQ_QC" 
output_folder: "/home/azadeh/workspace/snakemake_tutorial/snakemake-snakemake-tutorial-data-f17b467/output_QC_FASTQ_2023_test"
reference: "/home/azadeh/workspace/snakemake_tutorial/snakemake-snakemake-tutorial-data-f17b467/data" 

pair:
    R1 : R1
    R2 : R2
    
samples:
    QC_2023_nr11_filt : QC_2023_nr11_filt,
    QC_2023_nr12_filt : QC_2023_nr12_filt,
    QC_2023_nr13_filt : QC_2023_nr13_filt,
    QC_2023_nr14_filt : QC_2023_nr14_filt,
    QC_2023_nr15_filt : QC_2023_nr15_filt
